###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.0"
services:

    mysql:
      image: mysql:8.0
      container_name: csri-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=ZAINABlove1
        - MYSQL_DATABASE=CSRI
        - MYSQL_USER=hussnain
        - MYSQL_PASSWORD=ZAINABlove1
      ports:
        - "3308:3306"

    webserver:
      image: nginx:alpine
      container_name: csri-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "3306:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: csri-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
